### ISSUE TITLE
Can i use it in normal html website?

### ISSUE THREAD

**Issue by awsomedesigner** [Chalarangelo/mocka#1]
Hello guys

I recently working on my website. its a simple html, css website. I want to use mocka placeholder. Let me know how i can use mocka.

Thank you

**Comment by Chalarangelo** [comment]
Of course you can. Use as shown in its demo page, then, as soon as the content you are loading has loaded, swap out the placeholder for the content!

**Comment by Skippeh** [comment]
I don't see why not. It's only css styling.

Look at the readme for usage example.
